name: Main

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup haxe
      uses: haxeui/haxeui-core/.github/actions/haxe@master
      with:
        haxe-version: 4.1.1

    - name: Setup haxe dependencies
      run: |
        haxelib install dox
        haxelib install hxcpp

    - name: Setup GLFW dependencies
      run: sudo apt install xorg-dev --yes

    - name: Build and deploy documentation
      run: |
        haxe cppia_host.hxml -xml documentation/hxglfw.xml
        haxe sample.hxml
        haxelib run dox -o documentation/out/ -i documentation/hxglfw.xml -in glfw --title "hxglfw API reference" --toplevel-package glfw --keep-field-order -D version 0.0.1 -D source-path https://github.com/ibilon/hxglfw/blob/master/ -D website https://github.com/ibilon/hxglfw -D description "hxglfw is a work in progress haxe/hxcpp wrapper around GLFW"
        cd documentation/out
        git init
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ibilon/hxglfw
        git checkout -b gh-pages
        git add -A .
        git commit -m "Deploying documentation"
        git push -u origin gh-pages --force
